development: &development
  adapter: postgresql
  database: etymology_development
  username: developer
  password: password
  encoding: utf8
  template: template0

test: &test
  <<: *development
  database: etymology_test
